### ISSUE TITLE
Nametag problem

### ISSUE THREAD

**Issue by fortza** [Kondax/node-csgo-floats#4]
There is a problem nametag doesn't send. is null

**Comment by Kondax** [comment]
This isn't an issue on my end. This is just how the Game Coordinator replies.

**Comment by fortza** [comment]
and how at anothers module recive good replies ?

**Comment by Kondax** [comment]
This is using the 'other modules' (node-globaloffensice) to inspect the
items.

**Comment by fortza** [comment]
do have any idea how to get sticker image with sticker id ?

**Comment by Kondax** [comment]
No.
