### ISSUE TITLE
Anyway to Increase the time?

### ISSUE THREAD

**Issue by Dakssh** [Kondax/node-csgo-floats#7]
It just waits 15 seconds, is there anyway to increase it?

**Comment by Kondax** [comment]
There is no functionality delayed by 15 seconds.

Are you attempting to reference the timeout for the bots logging in or the time before removing an item from the queue?

**Comment by Dakshster** [comment]
This is what I was trying to do -

So, I was building a tradebot as you may have seen my activity on your Module(csgo-floats). So, I was kinda confused on how I should integrate Floats? If I restart the getting float process everytime I recieve a get request then It would be ridiculous and wouldn't work well. So I wanted to ask, what should I personally do to fix this issue

--
I wrote this discord for you, but after sending this message I found out that you removed me from discord.

**Comment by Kondax** [comment]
It shouldn't exceed more than 15 seconds to retrieve the item. I'm unsure why you need this increase.
