### ISSUE TITLE
Particular item took too long to resolve when resolving market items

### ISSUE THREAD

**Issue by Trahax** [Kondax/node-csgo-floats#9]
I've been getting the "Particular item took too long to resolve" when resolving items from the steam community market. I've tested items from other user's inventories as well as my own and the items resolve perfectly but when it passing an inspect URL from the steam community market it will always give "Particular item took too long to resolve". 

I've tested on sites such as csgo analyst and csgofloat.com and it gives me all the information required about the item. 

Any ideas what causes this?

**Comment by Trahax** [comment]
I've noticed in bot-master.js the m parameter is not actually passed in. Could this be the cause of the issue?

**Comment by Kondax** [comment]
Patched in #10
